### ISSUE TITLE
Cannot start SIP Proxy

### ISSUE THREAD

**Issue by github4tiri** [fonoster/routr#167]
How can we use the routr as SIP Proxy?

Using this, we tried to start the SIP Proxy. No port is spawn and browser connect is not possible. If you can provide us a config (no need to use rctl) to run a SIP Proxy, this would be great.
Here are the steps we ran.

```
sipuser@loc:~$ rctl version
[System info]
Server version: v1.0
API version: v1beta1
API path: /api/v1beta1
[Env]

sipuser@loc:~$ rctl proxy -p 9000

Serving Routr Console

You can now view the console in the browser.

  URL	http://localhost:9000

This is currently a beta software
All feedback is greatly appreciated!
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.
	at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
	at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
	at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:132)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.Toolkit$2.run(Toolkit.java:860)
	at java.awt.Toolkit$2.run(Toolkit.java:855)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)
	at java.awt.Desktop.isDesktopSupported(Desktop.java:169)
	at java.awt.Desktop.getDesktop(Desktop.java:143)
	at io.routr.ctl.CmdProxy.openBrowser(CmdProxy.java:138)
	at io.routr.ctl.CmdProxy.run(CmdProxy.java:123)
	at io.routr.ctl.Main.main(Main.java:143)
^C
```
Without X11 it does not work either.

```
sipuser@loc:~$ unset DISPLAY
sipuser@loc:~$ rctl proxy -p 9000

Serving Routr Console

You can now view the console in the browser.

  URL	http://localhost:9000

This is currently a beta software
All feedback is greatly appreciated!
java.net.SocketException: Operation not permitted
	at sun.nio.ch.Net.listen(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:221)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:85)
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:342)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:307)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:231)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.server.Server.doStart(Server.java:385)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at io.routr.ctl.CmdProxy.run(CmdProxy.java:124)
	at io.routr.ctl.Main.main(Main.java:143)
^C
```

Any help is highly appreciated.

**Comment by psanders** [comment]
@github4tiri From your logs I see you are running rctl (Routr Control). You need [Routr Server](https://github.com/fonoster/routr/tree/v1). This two tools ship separately.

**Comment by github4tiri** [comment]
Hello,

we were running routr server.


```
sudo snap install --edge rctl
wget https://github.com/fonoster/routr/releases/download/1.2.4/routr-1.2.4_linux-x64_bin.tar.gz -O - | tar xzf 
cd routr*x64_bin
perl -pi -e "s|level: info|level: debug|g" config/log4j2.yml
./routr
```

And then we used the rctl as mentioned above. Still the issue exist, so which might be wrong?
We need to proxy SIP.

Thanks for your help in advance!

**Comment by psanders** [comment]
I see. Do you get logs from running `./routr`? Also, which Linux distro are you using?

**Comment by github4tiri** [comment]
Hi Pedro,

I use Linux Mint / Ubuntu 20.04,

Here is console output when starting routr.

```
root@t480s:~/routr-1.2.4_linux-x64_bin# ./routr
[DEBUG] core.server_properties [server properties => {javax.net.ssl.trustStore=etc/certs/domains-cert.jks, gov.nist.javax.sip.MESSAGE_PROCESSOR_FACTORY=gov.nist.javax.sip.stack.NioMessageProcessorFactory, gov.nist.javax.sip.THREAD_POOL_SIZE=16, gov.nist.javax.sip.TLS_CLIENT_AUTH_TYPE=Want, gov.nist.javax.sip.TLS_CLIENT_PROTOCOLS=TLSv1.2, gov.nist.javax.sip.CACHE_CLIENT_CONNECTIONS=true, javax.net.ssl.keyStoreType=jks, gov.nist.javax.sip.MAX_TX_LIFETIME_NON_INVITE=60, gov.nist.javax.sip.REENTRANT_LISTENER=false, gov.nist.javax.sip.CANCEL_CLIENT_TRANSACTION_CHECKED=false, gov.nist.javax.sip.LOG_MESSAGE_CONTENT=false, javax.net.ssl.keyStorePassword=changeit, javax.sip.AUTOMATIC_DIALOG_SUPPORT=OFF, javax.sip.STACK_NAME=routr, javax.sip.IP_ADDRESS=127.0.1.1, gov.nist.javax.sip.NIO_BLOCKING_MODE=NONBLOCKING, gov.nist.javax.sip.MAX_TX_LIFETIME_INVITE=60, gov.nist.javax.sip.PATCH_SIP_WEBSOCKETS_HEADERS=false, javax.net.ssl.keyStore=etc/certs/domains-cert.jks, gov.nist.javax.sip.MAX_MESSAGE_SIZE=1048576}]
[INFO ] Starting Routr
[INFO ] Listening on 127.0.1.1:5060 [tcp]
[INFO ] Listening on 127.0.1.1:5060 [udp]
[INFO ] Listening on 127.0.1.1:5061 [tls]
[INFO ] Listening on 127.0.1.1:5062 [ws]
[INFO ] Listening on 127.0.1.1:5063 [wss]
[DEBUG] Starting Restful service server
[DEBUG] location.RouteLoader.loadStaticRoutes [loading static routes]
[DEBUG] loading route for key => sip:.{5,}@sip.local
[INFO ] Restful service server listening on port 4567
[DEBUG] Restful service server configuration: Config(
  apiPath = /api/v1beta1 
  bindAddr = 0.0.0.0 
  port = 4567
  unsecured = false
  keyStorePassword = /REDACTED/
  keyStore = etc/certs/api-cert.jks
  trustStore = etc/certs/api-cert.jks
  trustStorePassword = /REDACTED/
  maxThreads = 200
  minThreads = 8
  timeoutMillis = 5000
)
[DEBUG] Starting gRPC service, listening on 50099
[DEBUG] registry.Registry.registerAll [sending gateways registration]
```

Running these commands are fine:

```
root@t480s:~# rctl login https://127.0.0.1:4567/api/v1beta1 -u admin -p changeit
Done
root@t480s:~# rctl ping
up
```

**Comment by github4tiri** [comment]
Running the proxy fails:

```
# rctl proxy -p 15060

Serving Routr Console

You can now view the console in the browser.

  URL	http://localhost:15060

This is currently a beta software
All feedback is greatly appreciated!
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.
	at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
	at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
	at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:132)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.Toolkit$2.run(Toolkit.java:860)
	at java.awt.Toolkit$2.run(Toolkit.java:855)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)
	at java.awt.Desktop.isDesktopSupported(Desktop.java:169)
	at java.awt.Desktop.getDesktop(Desktop.java:143)
	at io.routr.ctl.CmdProxy.openBrowser(CmdProxy.java:138)
	at io.routr.ctl.CmdProxy.run(CmdProxy.java:123)
	at io.routr.ctl.Main.main(Main.java:143)

^C
```

And the workaround for mitigating the X11 error did not help (see above).

Besides that - maybe I am completely wrong with the approach and I have a wrong understanding of "proxy":

I am going to pass all SIP requests from my internal SIP devices over routr. Only the system which runs the routr Software should be able to talk to the internet. On my clients I want to configure the routr as the SIP Provider aka Proxy.

**Comment by psanders** [comment]
@github4tiri 

I believe I know now what's going on.

Few things. The purpose of `rctl proxy` is to launch the web app, not to proxy sip requests. You see an X11 error because the environment has no graphical interface. Run the rctl command on your local station. Not on the server.

Using rctl is not at all a requirement. And, it only makes sense if you are using routr + redis. Otherwise, you want to use the yaml files.

I want to encourage you to use [GH discussion](https://github.com/orgs/fonoster/discussions) and to post your use case so the community can help you.
