### ISSUE TITLE
Code installation failed: code is too large

### ISSUE THREAD

**Issue by psanders** [fonoster/routr#60]
This exception shows every once in awhile, but I don't have a way to reproduce it:

```
[truffle] opt fail         org.graalvm.polyglot.Value<InteropBoundFunction>.executeVoid|Reason jdk.vm.ci.code.BailoutException: Code installation failed: code is too large 
jdk.vm.ci.code.BailoutException: Code installation failed: code is too large
	at jdk.vm.ci.hotspot.HotSpotCodeCacheProvider.installCode(HotSpotCodeCacheProvider.java:150)
	at org.graalvm.compiler.core.target.Backend.createInstalledCode(Backend.java:194)
	at org.graalvm.compiler.core.target.Backend.createInstalledCode(Backend.java:147)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.compilePEGraph(TruffleCompilerImpl.java:531)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.compileAST(TruffleCompilerImpl.java:452)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:621)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:568)
	at org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:177)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.doCompile(TruffleCompilerImpl.java:280)
	at org.graalvm.compiler.truffle.compiler.hotspot.libgraal.HotSpotToSVMEntryPoints.doCompile(HotSpotToSVMEntryPoints.java:251)
```

**Comment by psanders** [comment]
I'm unable to reproduce the exception, but the following seems to be related:

```
[truffle] opt fail         doProcess                                                   |Reason org.graalvm.compiler.code.SourceStackTraceBailoutException$1: Partial evaluation did not reduce value to a constant, is a regular compiler node: 69694|Pi 
org.graalvm.compiler.code.SourceStackTraceBailoutException$1: Partial evaluation did not reduce value to a constant, is a regular compiler node: 69694|Pi
Caused by: org.graalvm.compiler.core.common.PermanentBailoutException: Partial evaluation did not reduce value to a constant, is a regular compiler node: 69694|Pi
	at org.graalvm.compiler.replacements.PEGraphDecoder$PENonAppendGraphBuilderContext.bailout(PEGraphDecoder.java:309)
	at org.graalvm.compiler.truffle.compiler.substitutions.TruffleGraphBuilderPlugins$20.apply(TruffleGraphBuilderPlugins.java:389)
	at org.graalvm.compiler.nodes.graphbuilderconf.InvocationPlugin.execute(InvocationPlugin.java:213)
	at org.graalvm.compiler.replacements.PEGraphDecoder.tryInvocationPlugin(PEGraphDecoder.java:795)
	at org.graalvm.compiler.replacements.PEGraphDecoder.trySimplifyInvoke(PEGraphDecoder.java:716)
	at org.graalvm.compiler.replacements.PEGraphDecoder.handleInvoke(PEGraphDecoder.java:696)
	at org.graalvm.compiler.nodes.GraphDecoder.processNextNode(GraphDecoder.java:584)
	at org.graalvm.compiler.nodes.GraphDecoder.decode(GraphDecoder.java:415)
	at org.graalvm.compiler.replacements.PEGraphDecoder.decode(PEGraphDecoder.java:619)
	at org.graalvm.compiler.truffle.compiler.PartialEvaluator.doGraphPE(PartialEvaluator.java:474)
	at org.graalvm.compiler.truffle.compiler.PartialEvaluator.fastPartialEvaluation(PartialEvaluator.java:512)
	at org.graalvm.compiler.truffle.compiler.PartialEvaluator.createGraph(PartialEvaluator.java:242)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.compileAST(TruffleCompilerImpl.java:438)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:621)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:568)
	at org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:177)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.doCompile(TruffleCompilerImpl.java:280)
	at org.graalvm.compiler.truffle.compiler.hotspot.libgraal.HotSpotToSVMEntryPoints.doCompile(HotSpotToSVMEntryPoints.java:251)
```

**Comment by psanders** [comment]
The following issue seems to be related https://github.com/oracle/graal/issues/1651
